//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SQLTools.rc
//
#define IDR_MANIFEST                    1
#define IDD_PROP_GRID1                  101
#define IDD_PROP_GRID2                  102
#define IDR_MAINFRAME                   128
#define IDR_SQLTYPE                     129
#define IDD_ABORT_QUERY                 130
#define IDD_DB_SOURCE                   131
#define IDM_GREP_POPUP                  131
#define IDR_LOAD_CODE_POPUP             132
#define IDR_OUTPUT_POPUP                133
#define IDR_GRID_POPUP                  134
#define IDB_SQLTOOLS                    135
#define IDR_EDIT_POPUP                  135
#define IDR_LS_LIST_POPUP               136
#define IDB_IMAGELIST3                  137
#define IDR_LS_OPTIONS_POPUP            137
#define IDR_LS_OTHER_POPUP              138
#define IDB_SQL_GENERAL_IMAGELIST       138
#define IDD_OBJ_INFO_TREE               139
#define IDI_AS_REPORT                   139
#define IDI_AS_LIST                     140
#define IDI_INVALID                     141
#define IDI_VALID                       142
#define IDI_REMOVE                      144
#define IDI_SQL_PLAN                    145
#define IDI_SQL_DESCRIBE                146
#define IDI_SQL_DB_SOURCE               147
#define IDI_FIND_FILES                  148
#define IDD_DBS_PROP                    151
#define IDD_EXTRACT_SCHEMA              153
#define IDT_CONNECT                     158
#define IDT_SQL                         158
#define IDT_FILE                        159
#define IDD_ES_OPTION_PAGE              163
#define IDD_TABLE_TRANSFOMER            165
#define IDR_ES_FOLDER_OPTIONS           169
#define IDI_ICONQUESTION                170
#define IDD_CONFIRMATION                171
#define IDD_CONNECT_DIALOG              173
#define IDD_GRID_OUTPUT_OPTIONS         175
#define IDD_PROP_GRID_OUTPUT            175
#define IDD_DB_TRUNCATE                 178
#define IDT_BOOKLET                     180
#define IDB_CONNECT                     182
#define IDD_INPUT                       184
#define IDD_INPUT_PASSWORD              185
#define IDB_IMAGELIST2                  201
#define IDB_IMAGELIST4                  202
#define IDB_FIND_FILES                  203
#define IDB_SORTDIRECTIONS              204
#define IDC_A_LOGO                      1000
#define IDC_C_USER                      1000
#define IDC_FF_MATH_WHOLE_WORD          1000
#define IDC_WORKBOOK_TAB                1000
#define IDC_A_LICENSE                   1001
#define IDC_ABOUTBOX_PRODUCT            1001
#define IDC_C_PASSWORD                  1001
#define IDC_FF_MATH_CASE                1001
#define IDC_ABOUTBOX_COMPANY            1002
#define IDC_C_CONNECT                   1002
#define IDC_FF_REG_EXPR                 1002
#define IDC_ABOUTBOX_VERSION            1003
#define IDC_FF_LOCK_IN_SUBFOLDERS       1003
#define IDC_C_TEST                      1003
#define IDC_ABOUTBOX_COPYRIGHT          1004
#define IDC_FF_SAVE_FILES               1004
#define IDC_FF_COLAPSED_LIST            1005
#define IDC_C_DELETE                    1005
#define IDC_C_HOST                      1006
#define IDC_C_TCP_PORT                  1007
#define IDC_C_SID                       1008
#define IDC_C_TNSCOPY                   1009
#define IDC_CL_COMPILE                  1013
#define IDC_CL_DELETE                   1014
#define IDC_CL_ENABLE                   1015
#define IDC_CL_DISABLE                  1016
#define IDC_CL_AS_LIST                  1017
#define IDC_CL_AS_REPORT                1018
#define IDC_CL_LOAD                     1035
#define IDC_DFP_NETWORK                 1037
#define IDC_CL_LOAD_ALL_IN_ONE          1038
#define IDC_DFP_HELP_BUTTON             1038
#define IDC_C_PROFILES                  1039
#define IDC_C_REMOVE_PROFILE            1040
#define IDC_DFP_READ_ONLY               1040
#define IDC_C_SAVE_PASSWORD             1041
#define IDC_SPIN1                       1042
#define IDC_C_DIRECT_CONNECTION         1042
#define IDC_GRID_PROP_MAX_COLUMN_LENGTH_SPIN 1042
#define IDC_SERV_PROP_OUTPUT_SIZE_SPIN1 1042
#define IDC_SERV_PROP_OUTPUT_SIZE_SPIN  1042
#define IDC_PROP_HIST_COUNT_SPIN        1042
#define IDC_SPIN2                       1043
#define IDC_C_SERVICE_INSTEAD_OF_SID    1043
#define IDC_GRID_PROP_ROWPREFETCH_SPIN  1043
#define IDC_PROP_HIST_SIZE_SPIN         1043
#define IDC_C_MODE                      1044
#define IDC_GRID_PROP_MAX_LOB_LENGTH_SPIN 1044
#define IDC_SERV_PROP_CANCEL_QUERY_DELAY_SPIN 1044
#define IDC_C_SAFETY                    1045
#define IDC_GRID_ROWPREFETCH_SPIN3      1045
#define IDC_GRID_PROP_MAX_BLOB_HEX_LENGTH_SPIN 1045
#define IDC_SPIN4                       1046
#define IDC_GRID_PROP_MULTILINE_COUNT_SPIN 1046
#define IDC_DFP_STATIC_DIR              1088
#define IDC_DFP_STATIC_TYPE             1089
#define IDC_DFP_STATIC_FILE_NAME        1090
#define IDC_DFP_STATIC_DRIVE            1091
#define IDC_EDIT_PROP_AUTO_INDENT       1100
#define IDC_EDIT_PROP_CREATE_FIRST_WINDOW_MAXIMIZED 1101
#define IDC_EDIT_PROP_DEFAULT_SELECTIONS 1102
#define IDC_EDIT_PROP_NO_HIDE_SELECTION_AFTER_PASTE 1103
#define IDC_EDIT_PROP_SYNTAX_HIGHLIGHT  1104
#define IDC_EDIT_PROP_TAB_SPACING       1105
#define IDC_EDIT_PROP_TAB_SPACING_SPIN  1106
#define IDC_EDIT_PROP_TABS              1107
#define IDC_EDIT_PROP_SPACES            1108
#define IDC_EDIT_PROP_WRAP_KEYS         1109
#define IDC_EDIT_PROP_TRUNC_SPACES      1110
#define IDC_EDIT_PROP_NORM_KEYWORDS     1112
#define IDC_EDIT_PROP_NORM_FUNC_KEYWORDS 1113
#define IDC_EDIT_PROP_NORM_USER_KEYWORDS 1114
#define IDC_DFP_FILE_LIST               1120
#define IDC_DFP_DIR_LIST                1121
#define IDC_DFP_TYPE_LIST               1136
#define IDC_DFP_DRIVE_LIST              1137
#define IDC_DFP_FILE_NAME               1152
#define IDC_SERV_PROP_DATE_FORMAT       1313
#define IDC_SERV_PROP_AUTOCOMMIT        1314
#define IDC_SERV_PROP_SAVE_PASSWORD     1315
#define IDC_DBSP_INDEXES                1315
#define IDC_SERV_PROP_OUTPUT_ENABLE     1316
#define IDC_DBSP_CONSTRAINTS            1316
#define IDC_SERV_PROP_SESSTAT           1317
#define IDC_DBSP_TRIGGERS               1317
#define IDC_SERV_PROP_TRUNC_SPACES      1318
#define IDC_DBSP_NO_STORAGE_FOR_PKUK    1318
#define IDC_SERV_PROP_ACTION_ON_DISCONNECT 1318
#define IDC_DBSP_GROUP_BY_DDL           1319
#define IDC_DBSP_COMMENTS               1320
#define IDC_DBSP_STORAGE_DISABLE        1321
#define IDC_DBSP_STORAGE_OVERRIDES      1322
#define IDC_DBSP_STORAGE_ALL            1323
#define IDC_DBSP_PRELOAD_DICTIONARY     1324
#define IDC_DBSP_SCHEMA_NAME            1325
#define IDC_DBSP_LOWER_NAMES            1326
#define IDC_DBSP_GRANTS                 1327
#define IDC_DBSP_SHOW_ON_SHIFT_ONLY     1328
#define IDC_DBSP_TABLE                  1329
#define IDC_DBSP_NO_PROMPTS             1329
#define IDC_DBSP_COMMENTS_AFTER_COLUMN  1330
#define IDC_DBSP_ALWAYS_SLASH           1330
#define IDC_DBSP_COMMENTS_POS           1331
#define IDC_DBSP_SPEC_WITH_BODY         1332
#define IDC_DBSP_BODY_WITH_SPEC         1333
#define IDC_DBSP_VIEW_WITH_TRIGGERS     1334
#define IDC_DBSP_SEQ_WITH_START         1335
#define IDC_DBSP_PRELOAD_START_PERCENT  1336
#define IDC_DBSP_VIEW_WITH_FORCE        1337
#define IDC_ES_TABLES                   1338
#define IDC_ES_VIEWS                    1339
#define IDC_ES_TRIGGERS                 1340
#define IDC_ES_CODE                     1341
#define IDC_ES_SELECT_FOLDER            1342
#define IDC_FF_SELECT_FOLDER            1342
#define IDC_ES_SCHEMA                   1343
#define IDC_FF_FILE_OR_TYPE             1343
#define IDC_ES_SEQUENCES                1344
#define IDC_FF_FOLDER                   1344
#define IDC_ES_SCHEMA2                  1344
#define IDC_TT_TABLE                    1344
#define IDC_ES_STATUS                   1345
#define IDC_FF_INSERT_EXPR              1345
#define IDC_ES_SYNONYMS                 1346
#define IDC_DS_TAB                      1347
#define IDC_ES_GRANTS_BY_GRANTEE        1347
#define IDC_DS_CANCEL                   1348
#define IDC_ESP_SCHEMA_NAME             1349
#define IDC_ESP_LOWER_NAMES             1350
#define IDC_ESP_SEQ_WITH_START          1351
#define IDC_ESP_COMMENTS_AFTER_COLUMN   1352
#define IDC_ESP_COMMENTS_POS            1353
#define IDC_ESP_GROUP_BY_DDL            1354
#define IDC_ESP_NO_STORAGE_FOR_PKUK     1355
#define IDC_ESP_STORAGE_DISABLE         1356
#define IDC_ESP_STORAGE_OVERRIDES       1357
#define IDC_ESP_STORAGE_ALL             1358
#define IDC_ESP_VIEW_WITH_FORCE         1359
#define IDC_ESP_SQLPLUS_COMPATIBILITY   1360
#define IDC_ESP_OPTIMAL_VIEW_ORDER      1361
#define IDC_TT_SCHEMA                   1361
#define IDC_ESP_ALWAYS_PUT_TABLESPACE   1362
#define IDC_DBSP_ALWAYS_PUT_TABLESPACE  1363
#define IDC_ES_TABLE_TABLESPACE         1364
#define IDC_ES_INDEX_TABLESPACE         1365
#define IDC_EDIT1                       1366
#define IDC_ES_FULL_PATH                1366
#define ID_CNF_TEXT                     1366
#define IDC_GOO_COMMA_CHAR              1366
#define IDC_DBD_COMMIT_AFTER            1366
#define IDC_SERV_PROP_PLAN_TABLE        1366
#define IDC_PROP_HIST_COUNT             1366
#define IDC_ABORT_CONNECTION            1366
#define IDC_INP_VALUE                   1366
#define IDC_DBD_COMMIT_AFTER_ROW        1367
#define IDC_GOO_QUOTE_CHAR              1367
#define IDC_PROP_HIST_SIZE              1367
#define IDC_ES_FOLDER_OPTIONS           1368
#define IDC_GOO_QUOTE_ESC_CHAR          1368
#define IDC_ABORT_ACTION                1368
#define IDC_GOO_PREFIX_CHAR             1369
#define ID_CNF_ALL                      1370
#define IDC_DBSP_SQLPLUS_COMPATIBILITY  1372
#define IDC_GOO_PLAIN_TEXT              1373
#define IDC_GOO_COMMA_DELIMITED         1374
#define IDC_GOO_TAB_DELIMITED           1375
#define IDC_GOO_XML_ELEM                1376
#define IDC_GOO_XML_ELEM_W_NAME         1378
#define IDC_GOO_XML_ATTR                1379
#define IDC_GRID_PROP_DATE_FORMAT       1379
#define IDC_GOO_WITH_HEADERS            1380
#define IDC_GRID_PROP_TIMESTAMP_FORMAT  1380
#define IDC_GRID_PROP_ALLOW_LESS_THAN_HEADER 1381
#define IDC_GOO_HTML                    1381
#define IDC_GRID_PROP_TIME_FORMAT       1381
#define IDC_GRID_PROP_ALLOW_REMEM_COL_WIDTH 1382
#define IDC_GRID_PROP_TIMESTAMP_TZ_FORMAT 1382
#define IDC_DBT_CHECK_DEPENDENCIES      1383
#define IDC_GRID_PROP_NUMBER_FORMAT     1383
#define IDC_DBC_DISABLE_FKS             1384
#define IDC_DBT_DISABLE_FKS             1384
#define IDC_DBC_SCRIPT_ONLY             1385
#define IDC_DBT_SCRIPT_ONLY             1385
#define IDC_DBT_KEEP_ALLOCATED          1386
#define IDC_DBD_DONT_COMMIT             1388
#define IDC_DBD_COMMIT                  1389
#define IDC_RADIO3                      1390
#define IDC_CHECK1                      1391
#define IDC_DBT_CASCADE                 1391
#define IDC_GRID_PROP_SKIP_LOBS         1391
#define IDC_PROP_HIST_ENABLE            1391
#define IDC_SERV_PROP_TOPMOST_CANCEL_QUERY 1391
#define IDC_SERV_PROP_OUTPUT_SIZE       1392
#define IDC_PROP_HIST_DISTINCT          1393
#define IDC_SERV_PROP_CANCEL_QUERY_DELAY 1393
#define IDC_SERV_PROP_DISPLAY_CURSOR    9999
#define IDC_SERV_PROP_WHITESPACE_DELIM  9998
#define IDC_SERV_PROP_SESSTAT_MODE      9997
#define IDC_PROP_HIST_INHERIT           1394
#define IDC_PROP_HIST_GLOBAL            1394
#define IDC_PROP_HIST_PERSISTENT        1395
#define IDC_PROP_HIST_VALID_ONLY        1396
#define IDC_PROP_HIST_ACTION_PASTE      1397
#define IDC_PROP_HIST_ACTION_REPLACE    1398
#define IDC_PROP_HIST_KEEP_SELECTION    1399
#define IDC_PROP_HIST_ACTION_COPY       1400
#define IDC_GRID_PROP_DEF_NUM_LENGTH    1401
#define IDC_GRID_PROP_MULTILINE_COUNT   1402
#define IDSTOP                          1402
#define IDC_GRID_PROP_MAX_COLUMN_LENGTH 1403
#define IDC_INP_PROMPT                  1403
#define IDC_GRID_PROP_DEF_DATE_LENGTH   1404
#define IDC_GRID_PROP_ROWPREFETCH       1404
#define IDC_OIT_INPUT                   1404
#define IDC_GRID_PROP_NULL_REPRESENTATION 1405
#define IDC_GRID_PROP_MAX_LOB_LENGTH    1406
#define IDC_GRID_PROP_MAX_BLOB_HEX_LENGTH 1407
#define IDC_GRID_PROP_DEF_DATE_LENGTH_SPIN 1408
#define IDC_OIT_TREE                    1501
#define IDC_DS_AS_LIST                  1601
#define IDC_DS_AS_REPORT                1602
#define IDC_DS_SCHEMA                   1603
#define IDC_DS_VALID                    1604
#define IDC_ES_FOLDER                   1604
#define IDC_FF_TEXT                     1604
#define IDC_DS_INVALID                  1605
#define IDC_DS_FILTER                   1606
#define IDC_DS_COPY                     1621
#define IDC_DS_LOAD                     1607
#define IDC_DS_LOAD_ALL_IN_ONE          1608
#define IDC_DS_COMPILE                  1609
#define IDC_DS_DELETE                   1610
#define IDC_DS_REFRESH                  1611
#define IDC_DS_OTHER                    1612
#define IDC_DS_OPTIONS                  1613
#define IDC_DS_ENABLE                   1614
#define IDC_DS_DISABLE                  1615
#define IDC_DS_STATUS                   1616
#define ID_DS_FILTER_ENABLED            1617
#define ID_DS_FILTER_BY_TABLES          1618
#define ID_DS_FILTER_FREE_FORMAT        1619
#define ID_DS_FILTER_BY_NAME            1620
#define IDD_DFP_DIRSELECT               2000
#define IDC_PFC_RESET_ALL               2001
#define IDC_PFC_ITEMS                   2002
#define IDC_EF_GLOBAL                   2003
#define IDC_EF_HELP                     2004
#define IDD_ABOUTBOX                    10000
#define IDD_CONNECT                     10001
#define IDD_PROP_SERVER                 10014
#define IDD_PLAN_VIEWER                 10016
#define IDD_DBS_PROP_TABLE              10017
#define IDD_FILE_FIND                   10019
#define IDD_WORKBOOK_BAR                10020
#define IDD_ES_FILTER_PAGE              10021
#define IDD_ES_MAIN_PAGE                10022
#define IDD_DB_DELETE                   10023
#define IDD_PROP_HISTORY                10024
#define ID_APP_SETTINGS                 0x8000
#define ID_GREP_CLEAR                   32772
#define ID_GREP_OPEN_FILE               32773
#define ID_GREP_COLLAPSE_ALL            32774
#define ID_GREP_EXPAND_ALL              32775
#define ID_BUTTON32789                  32789
#define ID_SQL_PREV_ERROR               32796
#define ID_SQL_HELP                     32799
#define ID_SQL_ERR_HELP                 32800
#define ID_SQL_OBJ_VIEWER               32801
#define ID_SQL_PLAN_VIEWER              32804
#define ID_CUSTOM_SPLITTER_DEF          32805
#define ID_CUSTOM_SPLITTER_DOWN         32807
#define ID_CUSTOM_SPLITTER_UP           32808
#define ID_WINDOW_CLOSE_ALL             32813
#define ID_PL_SQL_HELP                  32816
#define ID_SQL_DB_SOURCE                32818
#define ID_DS_SHOW_OPTIONS              32846
#define ID_VIEW_GEN_TOOLBAR             32858
#define ID_VIEW_FILE_TOOLBAR            32859
#define ID_VIEW_EDIT_TOOLBAR            32860
#define ID_VIEW_TEXT_TOOLBAR            32861
#define ID_VIEW_SQL_TOOLBAR             32862
#define ID_VIEW_SCRIPT_TOOLBAR          32863
#define ID_FILE_SHOW_GREP_OUTPUT        32864
#define ID_GREP_BREAK                   32865
#define ID_EDIT_DEL_LEFT_WORD           0x9006
#define ID_EDIT_DEL_RIGHT_WORD          0x9007
#define ID_EDIT_SEARCH_BRACE            0x9008
#define ID_INDICATOR_FIRST              0x9100
#define ID_INDICATOR_MODE               0x9100
#define ID_INDICATOR_OCIGRID            0x9104
#define ID_CUSTOM_NEXT_PANE             0x9200
#define ID_CUSTOM_PREV_PANE             37377
#define ID_CUSTOM_NEXT_TAB              0x9202
#define ID_CUSTOM_PREV_TAB              0x9203
#define ID_SQL_CONNECT                  0x9301
#define ID_SQL_DISCONNECT               0x9302
#define ID_SQL_COMMIT                   0x9303
#define ID_SQL_ROLLBACK                 0x9304
#define ID_SQL_DBMS_OUTPUT              0x9305
#define ID_SQL_EXTRACT_SCHEMA           0x9306
#define ID_SQL_SESSION_STATISTICS       0x9307
#define ID_SQL_DBMS_XPLAN_DISPLAY_CURSOR 0x9999
#define ID_SQL_TABLE_TRANSFORMER        0x9308
#define ID_SQL_EXPLAIN_PLAN             0x9408
#define ID_SQL_DESCRIBE                 0x9409
#define ID_SQL_EXECUTE                  0x940a
#define ID_SQL_EXECUTE_BELOW            0x940b
#define ID_SQL_EXECUTE_CURRENT          0x940c
#define ID_SQL_EXECUTE_CURRENT_AND_STEP 0x940d
#define ID_SQL_SUBSTITUTION_VARIABLES   0x940e
#define ID_SQL_REFRESH                  0x940f
#define ID_SQL_NEXT_ERROR               0x9410
#define ID_SQL_CURR_ERROR               0x9411
#define IDS_COMMANDS                    0x9412
#define ID_ES_USE_DB_ALIAS              38144
#define ID_ES_AS_DB_SCHEMA              38145
#define ID_ES_AS_SCHEMA_DB              38146
#define ID_ES_AS_DB_BKS_SCHEMA          38147
#define ID_SQL_LOAD                     38149
#define ID_SQLTOOLS_ON_THE_WEB          38150
#define ID_SQLTOOLS_UPDATE              40008
#define ID_GRID_OUTPUT_SAVE             38151
#define ID_GRID_OUTPUT_OPEN             38152
#define ID_GRID_OUTPUT_OPTIONS          38153
#define ID_GRID_OUTPUT_SAVE_AND_OPEN    38154
#define ID_GRID_COPY_ALL                38155
#define ID_GRID_COPY_ROW                38156
#define ID_OCIGRID_DATA_FIT             38157
#define ID_OCIGRID_COLS_TO_HEADERS      38158
#define ID_GRID_COPY_COL_HEADER         38159
#define ID_GRID_COPY_HEADERS            38160
#define ID_DS_DELETE                    38161
#define ID_DC_TRUNCATE                  38162
#define ID_DS_QUERY                     38163
#define ID_DS_TRUNCATE                  38164
#define ID_VIEW_CONNECT_TOOLBAR         38166
#define ID_BOOKLET_RESULT               38167
#define ID_BOOKLET_STATISTICS           38168
#define ID_BOOKLET_OUTPUT               38169
#define ID_BOOKLET_HISTORY              38170
#define ID_BOOKLET_SQL_PLAN             38171
#define ID_GRID_FIST_COMMAND            38172
#define ID_GRID_ROTATE                  38172
#define ID_GRID_MOVE_UP                 38173
#define ID_GRID_MOVE_FIST               38173
#define ID_GRID_MOVE_DOWN               38174
#define ID_GRID_MOVE_PGUP               38175
#define ID_GRID_MOVE_PGDOWN             38176
#define ID_GRID_MOVE_END                38177
#define ID_GRID_MOVE_HOME               38178
#define ID_GRID_DATA_FIT                38179
#define ID_GRID_HEADER_FIT              38180
#define ID_GRID_COPY_COL                38181
#define ID_GRID_SETTINGS                38182
#define ID_GRID_EXPORT                  38183
#define ID_GRID_OPEN_WITH_IE            38184
#define ID_GRID_OPEN_WITH_EXCEL         38185
#define ID_GRID_CLEAR                   38186
#define ID_GRID_LAST_COMMAND            38187
#define ID_SQL_HISTORY_GET_AND_STEPBACK 38190
#define ID_SQL_HISTORY_STEPFORWARD_AND_GET 38191
#define ID_SQL_HISTORY_GET              38192
#define ID_BOOKLET_PIN                  38193
#define ID_BOOKLET_UNPIN                38194
#define ID_BOOKLET_BINDS                38195
#define ID_NP_SWITCH_OLD_VIEW           40001
#define ID_NP_REFRESH                   40002
#define ID_GRID_POPUP                   40005
#define ID_GRIDPOPUP_WORDWRAP           40006
#define ID_GRIDPOPUP_CLOSE              40007
#define ID_DS_FLASHBACK                 40008
#define ID_DS_PURGE_ALL                 40009
// #define ID_NP_EDIT_COPY                 40003
// #define ID_NP_EDIT_SELECT_ALL           40004
#define IDR_NEWPLAN_OPTIONS             999
#define IDR_OBJECTVIEWER_DUMMY          998
#define IDR_OBJECTLIST_DUMMY            997
#define IDR_GRIDPOPUP_OPTIONS           996
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         38196
#define _APS_NEXT_CONTROL_VALUE         1405
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
