#define introduction 10
#define commandline 20
#define windows 200
#define ddlpreferences 240
#define hidd_connect_dialog 131245
#define hidd_extract_schema 131225
#define menus 300
#define filemenu 310
#define hid_file_new 123136
#define hid_file_open 123137
#define hid_file_update 123146
#define hid_file_close 123138
#define hid_window_close_all 98349
#define hid_file_save 123139
#define hid_file_save_as 123140
#define hid_file_save_all 0
#define hid_file_show_file_location 0
#define hid_file_page_setup 123141
#define hid_file_print_setup 123142
#define hid_file_print_preview 123145
#define hid_file_print 123143
#define hid_file_send_mail 123148
#define editmenu 320
#define hid_edit_undo 123179
#define hid_edit_redo 123180
#define hid_edit_cut 123171
#define hid_edit_copy 123170
#define hid_edit_paste 123173
#define editcutandappend 0
#define editcutbookmarkedlines 0
#define editcopyappend 0
#define editcopybookmarkedlines 0
#define editdelete 0
#define hid_edit_del_right_word 102407
#define hid_edit_del_left_word 102406
#define editdeleteline 0
#define editdeletebookmarkedlines 0
#define editselectword 0
#define editselectline 0
#define hid_edit_select_all 123178
#define editscrollup 0
#define editscrolltocenter 0
#define editscrolldown 0
#define viewmenu 330
#define viewfiletoolbar 0
#define viewsqltoolbar 0
#define viewconnectiontoolbar 0
#define hid_sql_obj_viewer 98337
#define databaseobjectslist 220
#define viewfindinfilesoutput 0
#define viewfilepanel 0
#define hidd_workbook_bar 141092
#define viewstatusbar 0
#define searchmenu 0
#define hid_edit_find 0
#define hid_edit_replace 123177
#define searchfindnext 0
#define searchfindprevious 0
#define searchgoto 0
#define searchtogglebookmark 0
#define searchnextbookmark 0
#define searchpreviousbookmark 0
#define searchremoveallbookmarks 0
#define searchsetrandombookmark 0
#define searchgetrandombookmark 0
#define searchfindmatch 102408
#define searchfindmatchselect 0
#define searchfindinfiles 0
#define textmenu 0
#define textstreamselection 0
#define textcolumnselection 0
#define texttoggleselectionmode 0
#define textsort 0
#define textindentselection 0
#define textundentselection 0
#define textuntabifyselection 0
#define texttabifyselectionall 0
#define texttabifyselectionleading 0
#define textnormalizekeyword 0
#define textlowercase 0
#define textuppercase 0
#define textcapitalize 0
#define textinvertcase 0
#define textcommentline 0
#define textuncommentline 0
#define textexpandtemplate 0
#define textdatetimestamp 0
#define textvisiblespaces 0
#define textlinenumbers 0
#define textruler 0
#define textcolumnmarkers 0
#define textfilesettingsinformation 0
#define gridmenu 0
#define sessionmenu 0
#define hid_sql_connect 103169
#define hid_sql_disconnect 103170
#define hid_sql_commit 103171
#define hid_sql_rollback 103172
#define hid_sql_dbms_output 103173
#define hid_sql_session_statistics 103175
#define scriptmenu 0
#define hid_sql_execute 103434
#define hid_sql_execute_current 103436
#define hid_sql_execute_current_and_step 103437
#define hid_sql_next_error 103440
#define hid_sql_prev_error 98332
#define scriptgethistoryandstepback 0
#define scriptstepforwardandgethistory 0
#define scriptfindobject 0
#define scriptloadddlscript 0
#define hid_sql_explain_plan 103432
#define hid_sql_substitution_variables 103438
#define toolsmenu 0
#define hid_sql_extract_schema 103174
#define hidd_table_transfomer 131237
#define toolssessionddlgridsetting 0
#define toolsapplicationeditorsettings 0
#define windowmenu 0
#define helpmenu 0
#define helphelptopics 0
#define hid_pl_sql_help 98352
#define hid_sqltools_on_the_web 103686
#define hidd_aboutbox 141072
#define toolbars 400
#define hid_view_file_toolbar 98395
#define hid_view_sql_toolbar 98398
#define hid_view_connect_toolbar 103702
#define printtoolbar 0
#define tools 500
#define bookmark 510
#define connectionlist 1001
#define directconnection 1002

